// GENERATED by scripts/build-emails.ts from lib/tokens.css — do not edit.
// Email clients can't read CSS variables, so the email layout takes these.
import type { EmailColors } from "./layout.ts";

export const EMAIL_COLORS: EmailColors = {
  "ink": "#1b2a2e",
  "inkSoft": "#5a6b6e",
  "paper": "#f2f4f3",
  "surface": "#ffffff",
  "rule": "#e8eaea",
  "verdigris": "#1e6b63"
};
