/*
 * The one layout every email Shulboard sends is built from — the invitations
 * the app sends itself (lib/email/send.ts) and the account emails Supabase Auth
 * sends (supabase/templates/, generated by scripts/build-emails.ts).
 *
 * Email clients can't read CSS variables, so the colours are passed in, taken
 * from lib/tokens.css by the build script (lib/email/colors.generated.ts) —
 * tokens.css stays the only place a colour is decided. Inline styles and a
 * table layout, because that is what Outlook and Gmail actually render.
 *
 * Same voice as the product: sentence case, one button, no "please", no
 * exclamation marks, nothing that looks like marketing.
 *
 * Pure: no imports that need a bundler, so the build script can run it.
 */

export type EmailColors = {
  ink: string;
  inkSoft: string;
  paper: string;
  surface: string;
  rule: string;
  verdigris: string;
};

export type EmailContent = {
  /** The line an inbox shows after the subject. */
  preheader: string;
  heading: string;
  /** Paragraphs, as HTML (callers escape anything a person typed). */
  paragraphs: string[];
  button?: { label: string; href: string };
  /** A code to show large, for emails that carry one (reauthentication). */
  code?: string;
  /** Small print under the button: why you got this, what to do if you didn't ask. */
  footnote?: string;
};

const FONT = "Assistant, 'Segoe UI', Helvetica, Arial, sans-serif";

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function emailHtml(content: EmailContent, colors: EmailColors): string {
  const p = (html: string) =>
    `<p style="margin:0 0 16px 0;font-family:${FONT};font-size:16px;line-height:24px;color:${colors.ink};">${html}</p>`;
  const button = content.button
    ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 24px 0;"><tr>
<td style="border-radius:5px;background:${colors.verdigris};">
<a href="${content.button.href}" style="display:inline-block;padding:12px 20px;font-family:${FONT};font-size:16px;font-weight:600;line-height:20px;color:${colors.surface};text-decoration:none;border-radius:5px;">${escapeHtml(content.button.label)}</a>
</td></tr></table>
<p style="margin:0 0 24px 0;font-family:${FONT};font-size:13px;line-height:20px;color:${colors.inkSoft};">If the button doesn&#39;t work, copy this address into your browser:<br><a href="${content.button.href}" style="color:${colors.verdigris};word-break:break-all;">${content.button.href}</a></p>`
    : "";
  const code = content.code
    ? `<p style="margin:8px 0 24px 0;font-family:${FONT};font-size:32px;font-weight:600;letter-spacing:6px;line-height:40px;color:${colors.ink};">${content.code}</p>`
    : "";
  const footnote = content.footnote
    ? `<p style="margin:0;padding-top:16px;border-top:1px solid ${colors.rule};font-family:${FONT};font-size:13px;line-height:20px;color:${colors.inkSoft};">${content.footnote}</p>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>${escapeHtml(content.heading)}</title>
</head>
<body style="margin:0;padding:0;background:${colors.paper};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${escapeHtml(content.preheader)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${colors.paper};">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;">
<tr><td style="padding:0 4px 16px 4px;font-family:${FONT};font-size:16px;font-weight:600;color:${colors.ink};">Shulboard</td></tr>
<tr><td style="background:${colors.surface};border:1px solid ${colors.rule};border-radius:6px;padding:32px 28px;">
<h1 style="margin:0 0 16px 0;font-family:${FONT};font-size:20px;font-weight:600;line-height:28px;color:${colors.ink};">${escapeHtml(content.heading)}</h1>
${content.paragraphs.map(p).join("\n")}
${code}${button}${footnote}
</td></tr>
<tr><td style="padding:16px 4px 0 4px;font-family:${FONT};font-size:12px;line-height:18px;color:${colors.inkSoft};">Shulboard runs the screens in your shul.</td></tr>
</table>
</td></tr>
</table>
</body>
</html>
`;
}

/** The plain-text part, for clients that don't show HTML and for spam scores. */
export function emailText(content: EmailContent): string {
  const strip = (html: string) =>
    html
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<[^>]+>/g, "")
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&amp;/g, "&");
  return [
    content.heading,
    "",
    ...content.paragraphs.map(strip).flatMap((line) => [line, ""]),
    ...(content.code ? [content.code, ""] : []),
    ...(content.button ? [`${content.button.label}: ${content.button.href}`, ""] : []),
    ...(content.footnote ? [strip(content.footnote)] : []),
  ].join("\n");
}
