/*
 * The board background library — pictures made for shul screens, shipped with
 * the product so every shul can use them. GENERATED by
 * scripts/add-backgrounds.mjs from the originals in backgrounds-src/; don't
 * edit the list by hand except to remove an entry (then delete its two files
 * from public/backgrounds/ too).
 *
 * Each entry is two files in public/backgrounds/: the picture itself (up to
 * 3840px, WebP) and a small thumbnail for the editor's grid. Both names carry a
 * content hash, so a replaced picture is a new URL and a screen that cached
 * the old one can't keep showing it. `tone` is the picture's measured
 * brightness, which is what switches a board's text to light on a dark one.
 */

export type LibraryBackground = {
  id: string;
  name: string;
  category: string;
  tone: "light" | "dark";
  /** Average relative luminance, 0–1 — lets a darkening veil re-derive the tone. */
  luminance: number;
  /** Path under the site root, e.g. "/backgrounds/candles-1a2b3c4d.webp". */
  src: string;
  thumb: string;
  width: number;
  height: number;
};

export const BACKGROUND_LIBRARY: LibraryBackground[] = /* BEGIN LIBRARY */ [] /* END LIBRARY */;
