/**
 * Writes the email templates from one layout (lib/email/layout.ts) and the
 * colours in lib/tokens.css:
 *
 *   supabase/templates/*.html        the account emails Supabase Auth sends
 *   lib/email/colors.generated.ts    the colours, for the invite the app sends
 *
 * Run with: npm run emails        (writes)
 *           npm run emails -- --check   (fails if anything is out of date)
 *
 * Email clients can't read CSS variables, which is the only reason colours
 * are copied out of tokens.css at all — copied by this script, never typed.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { emailHtml, type EmailColors } from "../lib/email/layout.ts";
import { AUTH_TEMPLATES } from "../lib/email/templates.ts";

const root = join(import.meta.dirname, "..");
const check = process.argv.includes("--check");
const tokens = readFileSync(join(root, "lib/tokens.css"), "utf8");

function token(name: string): string {
  const match = new RegExp(`--${name}:\\s*([^;]+);`).exec(tokens);
  if (!match) throw new Error(`lib/tokens.css has no --${name}`);
  return match[1].trim();
}

const colors: EmailColors = {
  ink: token("ink"),
  inkSoft: token("ink-soft"),
  paper: token("paper"),
  surface: token("surface"),
  // Hairlines are translucent in tokens.css; email clients handle rgba poorly,
  // so the rule is flattened onto the white card it sits on.
  rule: flatten(token("rule"), token("surface")),
  verdigris: token("verdigris"),
};

function flatten(rgba: string, over: string): string {
  const m = /rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)/.exec(rgba);
  const o = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(over);
  if (!m || !o) return rgba;
  const a = Number(m[4]);
  const mix = [1, 2, 3].map((i) => Math.round(Number(m[i]) * a + parseInt(o[i], 16) * (1 - a)));
  return `#${mix.map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}

const outputs = new Map<string, string>();
for (const template of AUTH_TEMPLATES) {
  outputs.set(join(root, "supabase/templates", template.file), emailHtml(template.content, colors));
}
outputs.set(
  join(root, "lib/email/colors.generated.ts"),
  `// GENERATED by scripts/build-emails.ts from lib/tokens.css — do not edit.
// Email clients can't read CSS variables, so the email layout takes these.
import type { EmailColors } from "./layout.ts";

export const EMAIL_COLORS: EmailColors = ${JSON.stringify(colors, null, 2)};
`,
);

let stale = 0;
for (const [path, content] of outputs) {
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {}
  if (current === content) continue;
  if (check) {
    console.log(`out of date: ${path.slice(root.length + 1)}`);
    stale += 1;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path.slice(root.length + 1)}`);
  }
}
if (check && stale > 0) {
  console.log("\nRun: npm run emails");
  process.exit(1);
}
if (check) console.log("Email templates match lib/email and lib/tokens.css.");
