/**
 * lib/media/image-size.ts — reading a photo's pixel size from its header, the
 * backfill's only source of truth for a photo stored before its size was
 * recorded. Real files, generated by sharp (which Next already ships), in every
 * format the reader claims — lossy and lossless WebP included, since those are
 * two different headers and the upload pipeline could write either.
 */

import sharp from "sharp";
import { readImageSize } from "../lib/media/image-size.ts";

const results: { ok: boolean; label: string }[] = [];
function check(ok: boolean, label: string, detail = "") {
  results.push({ ok, label });
  console.log(`${ok ? "  ok     " : "  FAILED "} ${label}${detail ? ` — ${detail}` : ""}`);
}

type Encoder = ReturnType<typeof sharp>;

const cases: [string, number, number, (s: Encoder) => Encoder][] = [
  ["lossy WebP (VP8)", 1080, 720, (s) => s.webp({ quality: 80 })],
  ["lossless WebP (VP8L)", 640, 960, (s) => s.webp({ lossless: true })],
  ["WebP with alpha (VP8X)", 777, 333, (s) => s.webp({ quality: 80, alphaQuality: 50 })],
  ["PNG", 400, 300, (s) => s.png()],
  ["JPEG", 1234, 567, (s) => s.jpeg({ quality: 70 })],
  ["progressive JPEG", 300, 1200, (s) => s.jpeg({ progressive: true })],
];

console.log("\n-- the header reader against real files ---------------------");
for (const [label, width, height, encode] of cases) {
  const channels = label.includes("alpha") ? 4 : 3;
  const base = sharp({
    create: { width, height, channels, background: channels === 4 ? { r: 30, g: 107, b: 99, alpha: 0.5 } : { r: 30, g: 107, b: 99 } },
  });
  const bytes = new Uint8Array(await encode(base).toBuffer());
  const size = readImageSize(bytes);
  check(size?.width === width && size?.height === height, `${label} reads ${width}×${height}`, size ? `${size.width}×${size.height}` : "null");
}

check(readImageSize(new Uint8Array([1, 2, 3, 4])) === null, "garbage reads as unknown, not a size");
check(readImageSize(new Uint8Array(0)) === null, "an empty file reads as unknown");

console.log("");
const failed = results.filter((r) => !r.ok).length;
console.log(`${results.length - failed}/${results.length} passed`);
process.exit(failed > 0 ? 1 : 0);
