// Generated by scripts/build-fonts.ts from the pinned @fontsource packages — don't edit.
// Run `npm run fonts` after changing lib/fonts/catalog.ts or a font package.

export type BuiltFace = { subset: string; style: "normal" | "italic"; weight: string; url: string; unicodeRange: string };

export type BuiltFont = {
  faces: BuiltFace[];
  /** Has the 'tnum' OpenType feature. */
  hasTabularNums: boolean;
  /** The widest digit, in em, at each offered weight. */
  digitEm: Record<number, number>;
  /** Its digits, as a time widget draws them, are already all one width. */
  digitsEqual: boolean;
  /** Has the 'lnum' OpenType feature. */
  hasLiningNums: boolean;
  /** Its digits as drawn (lnum on where it has it) are lining, not old-style. */
  liningDigits: boolean;
  /** Has a glyph for every digit 0–9. */
  digits: boolean;
  /** Covers A–Z, a–z and 0–9. */
  latin: boolean;
  /** Covers the Hebrew letters א–ת. */
  hebrew: boolean;
  /** Has every nikud point and positions them (GPOS mark). */
  nikud: boolean;
  metrics: { capHeight: number; xHeight: number; hebrewHeight: number | null };
};

export const BUILT_FONTS: Record<string, BuiltFont> = {
  "cinzel": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/cinzel/latin-wght-normal.09941fb1c1.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/cinzel/latin-ext-wght-normal.8fc2606f8a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.596,
      "500": 0.615,
      "600": 0.634,
      "700": 0.6531,
      "800": 0.6715,
      "900": 0.69
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.6,
      "hebrewHeight": null
    }
  },
  "playfair-display": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/playfair-display/latin-wght-normal.e0c764a8e9.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400 900",
        "url": "/fonts/playfair-display/latin-wght-italic.54af24bd0f.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/playfair-display/latin-ext-wght-normal.42898ad49a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400 900",
        "url": "/fonts/playfair-display/latin-ext-wght-italic.b9dff4aec6.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.607,
      "500": 0.6222,
      "600": 0.6374,
      "700": 0.6526,
      "800": 0.6678,
      "900": 0.683
    },
    "digitsEqual": false,
    "hasLiningNums": true,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.708,
      "xHeight": 0.515,
      "hebrewHeight": null
    }
  },
  "eb-garamond": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 800",
        "url": "/fonts/eb-garamond/latin-wght-normal.8860338416.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400 800",
        "url": "/fonts/eb-garamond/latin-wght-italic.c664773f7e.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 800",
        "url": "/fonts/eb-garamond/latin-ext-wght-normal.f8d3fa06e2.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400 800",
        "url": "/fonts/eb-garamond/latin-ext-wght-italic.fa866520f8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.48,
      "500": 0.4974,
      "600": 0.513,
      "700": 0.5292,
      "800": 0.54
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.653,
      "xHeight": 0.405,
      "hebrewHeight": null
    }
  },
  "cormorant-garamond": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 700",
        "url": "/fonts/cormorant-garamond/latin-wght-normal.d80df8ff5a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "300 700",
        "url": "/fonts/cormorant-garamond/latin-wght-italic.6f2f5c3b1a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 700",
        "url": "/fonts/cormorant-garamond/latin-ext-wght-normal.cfa9a397d8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "300 700",
        "url": "/fonts/cormorant-garamond/latin-ext-wght-italic.cd5bf126b2.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "500": 0.501,
      "600": 0.501,
      "700": 0.501
    },
    "digitsEqual": false,
    "hasLiningNums": true,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.625,
      "xHeight": 0.386,
      "hebrewHeight": null
    }
  },
  "libre-baskerville": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/libre-baskerville/latin-wght-normal.22219fb90e.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400 700",
        "url": "/fonts/libre-baskerville/latin-wght-italic.1203eb6186.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/libre-baskerville/latin-ext-wght-normal.8f7537ce3a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400 700",
        "url": "/fonts/libre-baskerville/latin-ext-wght-italic.890c2ae602.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.714,
      "700": 0.755
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.77,
      "xHeight": 0.53,
      "hebrewHeight": null
    }
  },
  "marcellus": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/marcellus/latin-400-normal.8a539799d1.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/marcellus/latin-ext-400-normal.1d5a987085.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.8062
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": false,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7002,
      "xHeight": 0.5,
      "hebrewHeight": null
    }
  },
  "dm-serif-display": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/dm-serif-display/latin-400-normal.fdf61e20fd.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/dm-serif-display/latin-400-italic.ed8b291611.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/dm-serif-display/latin-ext-400-normal.3af47815d6.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/dm-serif-display/latin-ext-400-italic.e026521e59.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.538
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.66,
      "xHeight": 0.481,
      "hebrewHeight": null
    }
  },
  "fraunces": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/fraunces/latin-wght-normal.7f9d191d99.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/fraunces/latin-ext-wght-normal.a21ecfbf41.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.6484,
      "500": 0.6618,
      "600": 0.6751,
      "700": 0.7018,
      "800": 0.7151,
      "900": 0.7285
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.481,
      "hebrewHeight": null
    }
  },
  "lora": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/lora/latin-wght-normal.ddb8c66035.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400 700",
        "url": "/fonts/lora/latin-wght-italic.d824d807d4.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/lora/latin-ext-wght-normal.2a2d9c22c9.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400 700",
        "url": "/fonts/lora/latin-ext-wght-italic.45f989df83.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.621,
      "500": 0.626,
      "600": 0.631,
      "700": 0.636
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.5,
      "hebrewHeight": null
    }
  },
  "crimson-pro": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 900",
        "url": "/fonts/crimson-pro/latin-wght-normal.20ce4189b9.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "200 900",
        "url": "/fonts/crimson-pro/latin-wght-italic.b3faa8f9ce.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 900",
        "url": "/fonts/crimson-pro/latin-ext-wght-normal.ac89a08a6e.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "200 900",
        "url": "/fonts/crimson-pro/latin-ext-wght-italic.01df7b443a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.5654,
      "500": 0.5774,
      "600": 0.5908,
      "700": 0.607,
      "800": 0.6239
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.5732,
      "xHeight": 0.4199,
      "hebrewHeight": null
    }
  },
  "bodoni-moda": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/bodoni-moda/latin-wght-normal.192ae876c2.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400 900",
        "url": "/fonts/bodoni-moda/latin-wght-italic.e50a00b843.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 900",
        "url": "/fonts/bodoni-moda/latin-ext-wght-normal.1186669811.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400 900",
        "url": "/fonts/bodoni-moda/latin-ext-wght-italic.f9db1bcce8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.6195,
      "500": 0.6306,
      "600": 0.6433,
      "700": 0.6593,
      "800": 0.6777,
      "900": 0.699
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.75,
      "xHeight": 0.46,
      "hebrewHeight": null
    }
  },
  "inter": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/inter/latin-wght-normal.3100e775e8.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/inter/latin-ext-wght-normal.34b9c504ca.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.646,
      "500": 0.6561,
      "600": 0.6662,
      "700": 0.6763,
      "800": 0.6917,
      "900": 0.7109
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7275,
      "xHeight": 0.5459,
      "hebrewHeight": null
    }
  },
  "montserrat": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/montserrat/latin-wght-normal.06b16db7a9.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "100 900",
        "url": "/fonts/montserrat/latin-wght-italic.0eb22e3d76.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/montserrat/latin-ext-wght-normal.54d9a78b7f.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "100 900",
        "url": "/fonts/montserrat/latin-ext-wght-italic.9f7c3dc0c1.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.6622,
      "500": 0.6686,
      "600": 0.6789,
      "700": 0.6891,
      "800": 0.7002,
      "900": 0.712
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.517,
      "hebrewHeight": null
    }
  },
  "lato": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/lato/latin-400-normal.918b7dc3e2.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/lato/latin-700-normal.c447dd7677.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "900",
        "url": "/fonts/lato/latin-900-normal.08664859ba.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/lato/latin-400-italic.bca1d88ada.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "700",
        "url": "/fonts/lato/latin-700-italic.6c84348296.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "900",
        "url": "/fonts/lato/latin-900-italic.d32335c2c5.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/lato/latin-ext-400-normal.8b9fc97370.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/lato/latin-ext-700-normal.3a5797f440.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "900",
        "url": "/fonts/lato/latin-ext-900-normal.e266d64fae.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/lato/latin-ext-400-italic.077a69d5b6.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "700",
        "url": "/fonts/lato/latin-ext-700-italic.72373c5fe4.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "900",
        "url": "/fonts/lato/latin-ext-900-italic.f9741d4c57.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.58,
      "700": 0.58,
      "900": 0.58
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7165,
      "xHeight": 0.5065,
      "hebrewHeight": null
    }
  },
  "josefin-sans": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 700",
        "url": "/fonts/josefin-sans/latin-wght-normal.21efe1559a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 700",
        "url": "/fonts/josefin-sans/latin-ext-wght-normal.e9dfe6f628.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.6235,
      "500": 0.6244,
      "600": 0.6253,
      "700": 0.628
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.702,
      "xHeight": 0.378,
      "hebrewHeight": null
    }
  },
  "raleway": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/raleway/latin-wght-normal.b1bef1f03a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/raleway/latin-ext-wght-normal.2d603982ca.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.6735,
      "500": 0.68,
      "600": 0.686,
      "700": 0.6926,
      "800": 0.6998,
      "900": 0.708
    },
    "digitsEqual": false,
    "hasLiningNums": true,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.71,
      "xHeight": 0.519,
      "hebrewHeight": null
    }
  },
  "outfit": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/outfit/latin-wght-normal.6c18d579fd.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/outfit/latin-ext-wght-normal.0f53d1c03b.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.656,
      "500": 0.655,
      "600": 0.6603,
      "700": 0.6655,
      "800": 0.6708,
      "900": 0.676
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.676,
      "xHeight": 0.46,
      "hebrewHeight": null
    }
  },
  "figtree": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/figtree/latin-wght-normal.4ba7d3d096.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/figtree/latin-ext-wght-normal.bf7828e2c2.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.6408,
      "500": 0.6429,
      "600": 0.6453,
      "700": 0.6482,
      "800": 0.6516,
      "900": 0.655
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.5,
      "hebrewHeight": null
    }
  },
  "work-sans": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/work-sans/latin-wght-normal.1dd49afc07.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/work-sans/latin-ext-wght-normal.2aa17fc7b0.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.622,
      "500": 0.6285,
      "600": 0.6357,
      "700": 0.6464,
      "800": 0.659,
      "900": 0.67
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.66,
      "xHeight": 0.5,
      "hebrewHeight": null
    }
  },
  "poppins": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/poppins/latin-400-normal.7d93459d86.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/poppins/latin-500-normal.cd36de204a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "600",
        "url": "/fonts/poppins/latin-600-normal.f4e80d9dfd.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/poppins/latin-700-normal.9338e65fc0.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "800",
        "url": "/fonts/poppins/latin-800-normal.60bf0aba65.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "900",
        "url": "/fonts/poppins/latin-900-normal.17ea10196a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/poppins/latin-ext-400-normal.0b1fcab42c.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/poppins/latin-ext-500-normal.af5fda16a1.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "600",
        "url": "/fonts/poppins/latin-ext-600-normal.bb1f2d582e.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/poppins/latin-ext-700-normal.ccfd87f69e.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "800",
        "url": "/fonts/poppins/latin-ext-800-normal.a72eccfa6c.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "900",
        "url": "/fonts/poppins/latin-ext-900-normal.0270140e61.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.635,
      "500": 0.647,
      "600": 0.661,
      "700": 0.677,
      "800": 0.691,
      "900": 0.704
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.697,
      "xHeight": 0.548,
      "hebrewHeight": null
    }
  },
  "abril-fatface": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/abril-fatface/latin-400-normal.edf7a1f3bc.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/abril-fatface/latin-ext-400-normal.c7cc6ab226.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.664
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.476,
      "hebrewHeight": null
    }
  },
  "bebas-neue": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bebas-neue/latin-400-normal.a7c90c8924.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bebas-neue/latin-ext-400-normal.16c95ce45a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.4
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.7,
      "hebrewHeight": null
    }
  },
  "oswald": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 700",
        "url": "/fonts/oswald/latin-wght-normal.bd73278ee0.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 700",
        "url": "/fonts/oswald/latin-ext-wght-normal.7989ccc777.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.517,
      "500": 0.534,
      "600": 0.543,
      "700": 0.55
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.81,
      "xHeight": 0.578,
      "hebrewHeight": null
    }
  },
  "great-vibes": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/great-vibes/latin-400-normal.c59dc73d29.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/great-vibes/latin-ext-400-normal.b63469c752.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.448
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.807,
      "xHeight": 0.357,
      "hebrewHeight": null
    }
  },
  "pinyon-script": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/pinyon-script/latin-400-normal.3e1f69a201.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/pinyon-script/latin-ext-400-normal.c208ba67b4.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.7305
    },
    "digitsEqual": false,
    "hasLiningNums": true,
    "liningDigits": false,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.6885,
      "xHeight": 0.3345,
      "hebrewHeight": null
    }
  },
  "parisienne": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/parisienne/latin-400-normal.cf3c285d1e.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/parisienne/latin-ext-400-normal.652fa5786f.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.7197
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": false,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7446,
      "xHeight": 0.353,
      "hebrewHeight": null
    }
  },
  "dancing-script": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/dancing-script/latin-wght-normal.51acdc0e00.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/dancing-script/latin-ext-wght-normal.35f77ad59c.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.63,
      "500": 0.6399,
      "600": 0.6498,
      "700": 0.66
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.72,
      "xHeight": 0.332,
      "hebrewHeight": null
    }
  },
  "caveat": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/caveat/latin-wght-normal.891951df5e.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/caveat/latin-ext-wght-normal.f626b95c1e.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.45,
      "500": 0.457,
      "600": 0.464,
      "700": 0.471
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": false,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7005,
      "xHeight": 0.3551,
      "hebrewHeight": null
    }
  },
  "frank-ruhl-libre": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/frank-ruhl-libre/latin-wght-normal.b8081e5e9a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/frank-ruhl-libre/latin-ext-wght-normal.0ec100915c.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/frank-ruhl-libre/hebrew-wght-normal.acdf9ed0a3.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "300": 0.551,
      "400": 0.557,
      "500": 0.586,
      "600": 0.5934,
      "700": 0.5998,
      "800": 0.6044,
      "900": 0.609
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.66,
      "xHeight": 0.468,
      "hebrewHeight": 0.586
    }
  },
  "david-libre": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/david-libre/latin-400-normal.fd102665a4.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/david-libre/latin-500-normal.ccd127367d.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/david-libre/latin-700-normal.c36ca4cfb8.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/david-libre/latin-ext-400-normal.16a4356ea2.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/david-libre/latin-ext-500-normal.8e7342a52a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/david-libre/latin-ext-700-normal.bf296324f8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/david-libre/hebrew-400-normal.9dedc029ea.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/david-libre/hebrew-500-normal.08f5b82d26.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/david-libre/hebrew-700-normal.1b4fc13688.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.499,
      "500": 0.499,
      "700": 0.5049
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.6152,
      "xHeight": 0.4541,
      "hebrewHeight": 0.5278
    }
  },
  "noto-serif-hebrew": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-serif-hebrew/latin-wght-normal.621141beab.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-serif-hebrew/latin-ext-wght-normal.f8a07051f7.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-serif-hebrew/hebrew-wght-normal.b5535c575a.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "100": 0.559,
      "200": 0.559,
      "300": 0.559,
      "400": 0.559,
      "500": 0.5606,
      "600": 0.5626,
      "700": 0.5648,
      "800": 0.5671,
      "900": 0.569
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.714,
      "xHeight": 0.536,
      "hebrewHeight": 0.647
    }
  },
  "bona-nova": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bona-nova/latin-400-normal.b7aa3adb6b.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/bona-nova/latin-700-normal.c5b83caa01.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/bona-nova/latin-400-italic.52d165ad88.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bona-nova/latin-ext-400-normal.47f25065dc.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/bona-nova/latin-ext-700-normal.ff3e948fda.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/bona-nova/latin-ext-400-italic.cafd33d16f.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bona-nova/hebrew-400-normal.8afed45a7d.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/bona-nova/hebrew-700-normal.536ff93fd6.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "italic",
        "weight": "400",
        "url": "/fonts/bona-nova/hebrew-400-italic.9a11e1d860.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.605,
      "700": 0.699
    },
    "digitsEqual": false,
    "hasLiningNums": true,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.665,
      "xHeight": 0.44,
      "hebrewHeight": 0.585
    }
  },
  "heebo": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/heebo/latin-wght-normal.50dae2e12d.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/heebo/latin-ext-wght-normal.dd3af41d4e.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/heebo/hebrew-wght-normal.f1f7cfaef5.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "100": 0.5474,
      "200": 0.5522,
      "300": 0.5566,
      "400": 0.562,
      "500": 0.5656,
      "600": 0.57,
      "700": 0.574,
      "800": 0.578,
      "900": 0.582
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.7109,
      "xHeight": 0.5283,
      "hebrewHeight": 0.5773
    }
  },
  "assistant": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 800",
        "url": "/fonts/assistant/latin-wght-normal.26b77cc317.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 800",
        "url": "/fonts/assistant/latin-ext-wght-normal.5e2544c155.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "200 800",
        "url": "/fonts/assistant/hebrew-wght-normal.f9805e7a16.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "200": 0.472,
      "300": 0.4822,
      "400": 0.4924,
      "500": 0.4992,
      "600": 0.506,
      "700": 0.523,
      "800": 0.54
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.66,
      "xHeight": 0.478,
      "hebrewHeight": 0.5456
    }
  },
  "rubik": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/rubik/latin-wght-normal.691cd1d9b4.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "300 900",
        "url": "/fonts/rubik/latin-wght-italic.4d9f552c4b.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/rubik/latin-ext-wght-normal.09472f217a.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "300 900",
        "url": "/fonts/rubik/latin-ext-wght-italic.51999fc7e4.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "300 900",
        "url": "/fonts/rubik/hebrew-wght-normal.197b6dbe5c.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "italic",
        "weight": "300 900",
        "url": "/fonts/rubik/hebrew-wght-italic.8f5e07ecc6.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "300": 0.618,
      "400": 0.6356,
      "500": 0.6574,
      "600": 0.6683,
      "700": 0.6825,
      "800": 0.7088,
      "900": 0.735
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.52,
      "hebrewHeight": 0.571
    }
  },
  "ibm-plex-sans-hebrew": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-100-normal.ac67b8c98b.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-200-normal.eab52ab175.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-300-normal.c50b8beeda.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-400-normal.f3f80a783f.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-500-normal.f21bfcb259.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "600",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-600-normal.8216c868e9.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-700-normal.a07b17697a.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-100-normal.d02d49fdcf.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-200-normal.22a839dba4.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-300-normal.06047f0a47.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-400-normal.4e1d19a7c8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-500-normal.9ba0ded790.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "600",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-600-normal.d9e4f285ec.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/ibm-plex-sans-hebrew/latin-ext-700-normal.0e33bee96c.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "100",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-100-normal.aeeb226ee1.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "200",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-200-normal.63a5da3bf1.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-300-normal.bc59ed98b8.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-400-normal.087793392c.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "500",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-500-normal.3f85b2d84d.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "600",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-600-normal.2a0832e31c.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/ibm-plex-sans-hebrew/hebrew-700-normal.7127a3cf5a.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "100": 0.6,
      "200": 0.6,
      "300": 0.6,
      "400": 0.6,
      "500": 0.6,
      "600": 0.6,
      "700": 0.6
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": false,
    "metrics": {
      "capHeight": 0.698,
      "xHeight": 0.516,
      "hebrewHeight": 0.5984
    }
  },
  "alef": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/alef/latin-400-normal.5fae182e54.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/alef/latin-700-normal.1baa62c929.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/alef/hebrew-400-normal.2cbc94e227.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/alef/hebrew-700-normal.ced6261be3.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.6089,
      "700": 0.6108
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": false,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": false,
    "metrics": {
      "capHeight": 0.7021,
      "xHeight": 0.519,
      "hebrewHeight": 0.5244
    }
  },
  "suez-one": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/suez-one/latin-400-normal.da1b72c459.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/suez-one/latin-ext-400-normal.39526bf239.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/suez-one/hebrew-400-normal.b133f829d7.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.65
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": false,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.674,
      "xHeight": 0.523,
      "hebrewHeight": 0.5842
    }
  },
  "secular-one": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/secular-one/latin-400-normal.3fbb660178.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/secular-one/latin-ext-400-normal.96849d6d09.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/secular-one/hebrew-400-normal.c1e45f5b97.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.586
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.666,
      "xHeight": 0.523,
      "hebrewHeight": 0.5396
    }
  },
  "bellefair": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bellefair/latin-400-normal.8ab33f207b.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bellefair/latin-ext-400-normal.bf97432276.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/bellefair/hebrew-400-normal.4050efdac5.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.522
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.6889,
      "xHeight": 0.3641,
      "hebrewHeight": 0.456
    }
  },
  "karantina": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/karantina/latin-300-normal.0434cf6a31.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/karantina/latin-400-normal.d266ef8ddd.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/karantina/latin-700-normal.e25d8653a0.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/karantina/latin-ext-300-normal.d7aebb5ffb.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/karantina/latin-ext-400-normal.14916ae9b5.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/karantina/latin-ext-700-normal.b61ded7392.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "300",
        "url": "/fonts/karantina/hebrew-300-normal.c1e6e38762.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/karantina/hebrew-400-normal.ba421f0d06.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/karantina/hebrew-700-normal.0d8ca903dd.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "300": 0.294,
      "400": 0.347,
      "700": 0.383
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.7,
      "xHeight": 0.5,
      "hebrewHeight": 0.6
    }
  },
  "amatic-sc": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/amatic-sc/latin-400-normal.9ee1dd0b37.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/amatic-sc/latin-700-normal.5d37fcdf66.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/amatic-sc/latin-ext-400-normal.4ca7885bff.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/amatic-sc/latin-ext-700-normal.d3dbc2c5b8.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400",
        "url": "/fonts/amatic-sc/hebrew-400-normal.f6dee43bcd.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "700",
        "url": "/fonts/amatic-sc/hebrew-700-normal.1eed9349a4.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "400": 0.338,
      "700": 0.343
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.758,
      "xHeight": 0.662,
      "hebrewHeight": 0.6612
    }
  },
  "noto-rashi-hebrew": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-rashi-hebrew/latin-wght-normal.4009fe7f5b.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-rashi-hebrew/latin-ext-wght-normal.41d5168201.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "100 900",
        "url": "/fonts/noto-rashi-hebrew/hebrew-wght-normal.1e5e568b41.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "100": 0.559,
      "200": 0.559,
      "300": 0.559,
      "400": 0.559,
      "500": 0.5609,
      "600": 0.5628,
      "700": 0.565,
      "800": 0.5672,
      "900": 0.569
    },
    "digitsEqual": true,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.714,
      "xHeight": 0.536,
      "hebrewHeight": 0.6336
    }
  },
  "playpen-sans-hebrew": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 800",
        "url": "/fonts/playpen-sans-hebrew/latin-wght-normal.a3f43e8e62.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 800",
        "url": "/fonts/playpen-sans-hebrew/latin-ext-wght-normal.622e0d29c1.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "100 800",
        "url": "/fonts/playpen-sans-hebrew/hebrew-wght-normal.f22ac20757.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": false,
    "digitEm": {
      "100": 0.715,
      "200": 0.7215,
      "300": 0.7279,
      "400": 0.735,
      "500": 0.7333,
      "600": 0.7315,
      "700": 0.7296,
      "800": 0.728
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.782,
      "xHeight": 0.546,
      "hebrewHeight": 0.5984
    }
  },
  "miriam-libre": {
    "faces": [
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/miriam-libre/latin-wght-normal.484e152d07.woff2",
        "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/miriam-libre/latin-ext-wght-normal.be502712ca.woff2",
        "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "subset": "hebrew",
        "style": "normal",
        "weight": "400 700",
        "url": "/fonts/miriam-libre/hebrew-wght-normal.5b339ebe00.woff2",
        "unicodeRange": "U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F"
      }
    ],
    "hasTabularNums": true,
    "digitEm": {
      "400": 0.595,
      "500": 0.6037,
      "600": 0.6123,
      "700": 0.621
    },
    "digitsEqual": false,
    "hasLiningNums": false,
    "liningDigits": true,
    "digits": true,
    "latin": true,
    "hebrew": true,
    "nikud": true,
    "metrics": {
      "capHeight": 0.695,
      "xHeight": 0.566,
      "hebrewHeight": 0.581
    }
  }
};

/** Each Hebrew face's size-matched, Hebrew-only family: `base` for any
 *  English face, and a per-pairing one where an English face needs its own. */
export const HEBREW_ALIASES: Record<string, { base: { family: string; sizeAdjust: number }; pairings: Record<string, { family: string; sizeAdjust: number }> }> = {
  "frank-ruhl-libre": {
    "base": {
      "family": "Frank Ruhl Libre Hebrew",
      "sizeAdjust": 1.02
    },
    "pairings": {
      "cinzel": {
        "family": "Frank Ruhl Libre Hebrew for Cinzel",
        "sizeAdjust": 1.19
      },
      "eb-garamond": {
        "family": "Frank Ruhl Libre Hebrew for EB Garamond",
        "sizeAdjust": 0.9
      },
      "cormorant-garamond": {
        "family": "Frank Ruhl Libre Hebrew for Cormorant Garamond",
        "sizeAdjust": 0.86
      },
      "libre-baskerville": {
        "family": "Frank Ruhl Libre Hebrew for Libre Baskerville",
        "sizeAdjust": 1.11
      },
      "crimson-pro": {
        "family": "Frank Ruhl Libre Hebrew for Crimson Pro",
        "sizeAdjust": 0.85
      }
    }
  },
  "david-libre": {
    "base": {
      "family": "David Libre Hebrew",
      "sizeAdjust": 1.12
    },
    "pairings": {}
  },
  "noto-serif-hebrew": {
    "base": {
      "family": "Noto Serif Hebrew Hebrew",
      "sizeAdjust": 0.91
    },
    "pairings": {}
  },
  "bona-nova": {
    "base": {
      "family": "Bona Nova Hebrew",
      "sizeAdjust": 1.01
    },
    "pairings": {}
  },
  "heebo": {
    "base": {
      "family": "Heebo Hebrew",
      "sizeAdjust": 1.01
    },
    "pairings": {
      "inter": {
        "family": "Heebo Hebrew for Inter",
        "sizeAdjust": 1.1
      },
      "bebas-neue": {
        "family": "Heebo Hebrew for Bebas Neue",
        "sizeAdjust": 1.21
      },
      "oswald": {
        "family": "Heebo Hebrew for Oswald",
        "sizeAdjust": 1.2
      },
      "pinyon-script": {
        "family": "Heebo Hebrew for Pinyon Script",
        "sizeAdjust": 0.89
      },
      "dancing-script": {
        "family": "Heebo Hebrew for Dancing Script",
        "sizeAdjust": 0.91
      },
      "caveat": {
        "family": "Heebo Hebrew for Caveat",
        "sizeAdjust": 0.91
      }
    }
  },
  "assistant": {
    "base": {
      "family": "Assistant Hebrew",
      "sizeAdjust": 1.08
    },
    "pairings": {}
  },
  "rubik": {
    "base": {
      "family": "Rubik Hebrew",
      "sizeAdjust": 1.03
    },
    "pairings": {}
  },
  "ibm-plex-sans-hebrew": {
    "base": {
      "family": "IBM Plex Sans Hebrew Hebrew",
      "sizeAdjust": 0.98
    },
    "pairings": {}
  },
  "alef": {
    "base": {
      "family": "Alef Hebrew",
      "sizeAdjust": 1.12
    },
    "pairings": {}
  },
  "suez-one": {
    "base": {
      "family": "Suez One Hebrew",
      "sizeAdjust": 1.01
    },
    "pairings": {}
  },
  "secular-one": {
    "base": {
      "family": "Secular One Hebrew",
      "sizeAdjust": 1.09
    },
    "pairings": {}
  },
  "bellefair": {
    "base": {
      "family": "Bellefair Hebrew",
      "sizeAdjust": 1.29
    },
    "pairings": {}
  },
  "karantina": {
    "base": {
      "family": "Karantina Hebrew",
      "sizeAdjust": 0.98
    },
    "pairings": {}
  },
  "amatic-sc": {
    "base": {
      "family": "Amatic SC Hebrew",
      "sizeAdjust": 0.89
    },
    "pairings": {}
  },
  "noto-rashi-hebrew": {
    "base": {
      "family": "Noto Rashi Hebrew Hebrew",
      "sizeAdjust": 0.93
    },
    "pairings": {}
  },
  "playpen-sans-hebrew": {
    "base": {
      "family": "Playpen Sans Hebrew Hebrew",
      "sizeAdjust": 0.98
    },
    "pairings": {}
  },
  "miriam-libre": {
    "base": {
      "family": "Miriam Libre Hebrew",
      "sizeAdjust": 1.01
    },
    "pairings": {}
  }
};

/** The stylesheet declaring every face (the root layout links it). */
export const FONT_FACES_CSS = "/fonts/faces.3124d82afb.css";
